name: Build and Push to Docker Hub

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show context (for debugging)
        run: |
          echo "GitHub ref: $GITHUB_REF"
          echo "Run number: $GITHUB_RUN_NUMBER"

      - name: Log in to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: |
          IMAGE="${{ secrets.DOCKER_USERNAME }}/is147:${{ github.run_number }}"
          echo "Building image $IMAGE"
          docker build -t "$IMAGE" .

      - name: Push Docker Image
        run: |
          IMAGE="${{ secrets.DOCKER_USERNAME }}/is147:${{ github.run_number }}"
          echo "Pushing image $IMAGE"
          docker push "$IMAGE"
